# Generated by Django 3.2.13 on 2022-06-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20220620_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catagory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='pc', max_length=255),
        ),
    ]
